name: dragonflylabs
description: Our lab develops specific solutions for any problem you might have.
  We specialize in different areas, like mobile development, system automations,
  and sports technologies.

publish_to: "none"

version: 2.0.0+2.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.2
  flutter_svg: ^2.0.9
  flutter_triple: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.6
  flutter_test:
    sdk: flutter

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#000020"
  image: assets/branding/icon.png
  web_image_mode: center
  web_splash_fade_time_ms: 250

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
