name: portifolio
description: PortifÃ³lio Pessoal de Pedro Henrique Cordeiro Soares.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  bloc: ^7.0.0
  cloud_firestore: ^2.2.0
  cupertino_icons: ^1.0.3
  equatable: ^2.0.2
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_storage: ^8.1.0
  flutter_bloc: ^7.0.1
  flutter_colorpicker: ^0.4.0
  get_it: ^7.1.3
  google_sign_in: ^5.0.4
  image_cropper: ^1.4.0
  image_picker: ^0.8.0
  intl: ^0.17.0
  logger: ^1.0.0
  url_launcher: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: false
  android: true
  image_path: "assets/images/iconphcs.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/qb1.jpg
    - assets/images/icon.png

  fonts:
    - family: ExtraTechIcons
      fonts:
        - asset: assets/fonts/ExtraTechIcons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
