name: portifolio
description: PortifÃ³lio Pessoal de Pedro Henrique Cordeiro Soares.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  equatable: ^1.2.5
  get_it: ^4.0.4
  logger: ^0.9.2
  flutter_icons: ^1.1.0
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  url_launcher: ^5.6.0
  intl: ^0.16.1
  google_sign_in: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: false
  android: true
  image_path: "assets/images/iconphcs.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/qb1.jpg
    - assets/images/icon.png

  fonts:
    - family: ExtraTechIcons
      fonts:
        - asset: assets/fonts/ExtraTechIcons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

